export const Colors = {
  white: "#FFF",
  backgroundColorBody: "#D2DBDC",
  backgroundColorAppWindow: "#EDEDED",
  colorIcons: "#919191",
  backgroundColorSearch: "#F6F6F6",
  hoverChatList: "#F5F5F5",
  chatIntroBackgroundColor: "#F8F9FA",
  chatListActiveChat: "#EBEBEB",
  colorSelectIcons: "#009688",
  gray: "#DDD",
  graySearch: "#EEE",
  grayChat: "#525252",
  green: "#4adf83",
  darkGray: "#777",
  grayChatList: "#999",
  black: "#000",
  grayChatWindow: "#CCC",
  grayChatWindowBody: "#E5DDD5",
  grayFooter: "#4A4A4A",
  micActiveColor: "#126ECE",
};
